<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>ecdc1fc6-c5a5-4c49-b7c0-5234c9ee191f</UserSecretsId>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>DotNetFrame</PackageId>
		<Version>1.0.3</Version>
		<Authors>Umut Yurdugul</Authors>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Description>z/OSMF REST API wrapper for .NET applications.</Description>
		<PackageTags>mainframe;zosmf;zos;api;wrapper;jcl</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
	</ItemGroup>

</Project>
